#spring:
#  datasource:
#    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
#    username: "RM553215"
#    password: "160701"
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#    database-platform: org.hibernate.dialect.OracleDialect

spring:
  datasource:
    url: jdbc:h2:mem:meu_banco_h2
    driverClassName: org.h2.Driver
    username: sa
    password: keven123
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect